### ISSUE TITLE
Harp installation 

### ISSUE THREAD

**Issue by Thatguy027** [petrov-lab/HAFpipe-line#1]
Hello,

I am having a hard time installing harp on my mac and am wondering if you had any tips for installation - I figured I'd ask here before harp because the harp repository is quite old and I am unsure if the developers are responsive.

The error I get when trying to build harp is:

```
In file included from preprocess_pcr_fastq.cpp:36:
./BAMFile.hpp:41:10: fatal error: 'tr1/memory' file not found
#include <tr1/memory>
         ^~~~~~~~~~~~
1 error generated.

    "g++"   -O0 -fno-inline -Wall -Werror -g     -c -o "../build/gcc-4.2.1/debug/link-static/preprocess_pcr_fastq.o" "preprocess_pcr_fastq.cpp"

...failed gcc.compile.c++ ../build/gcc-4.2.1/debug/link-static/preprocess_pcr_fastq.o...
...skipped <p../build/gcc-4.2.1/debug/link-static/runtime-link-static>preprocess_pcr_fastq for lack of <p../build/gcc-4.2.1/debug/link-static>preprocess_pcr_fastq.o...
...skipped <p../bin>preprocess_pcr_fastq for lack of <p../build/gcc-4.2.1/debug/link-static>preprocess_pcr_fastq.o...
...failed updating 48 targets...
...skipped 67 targets...
```

For all the files with `tr1/memory` in them.

Searching around stackoverflow and other places suggests that this is a compiler and code issue ([link](https://stackoverflow.com/questions/42030598/mac-c-compiler-not-finding-tr1-unordered-map)). 

There is a note at the end of the Jamroot file:

```
#
# static link issue: 
#   - by default, XCode gcc links to .dylib if it finds one, even if it found a static lib first in
#     a different directory (!)
#   - darwin toolset doesn't allow <link>static specification for searched libs
#   - this means that */<link>static has no effect on OSX
#
# OSX workaround: remove .dylibs from ALL searched dirs
# alternate OSX workaround: give full filename of lib*.a on g++ command line
#
# linux: boost_filesystem/<link>static does indeed link to the boost_*.a files
#
```

But I am unsure how to implement this suggestion.

Any help would be greatly appreciated!

Thanks

**Comment by JamieCFreeman** [comment]
Hi-

Not one of the developers, but I was able to download a compiled version of harp from:
https://bitbucket.org/dkessner/harp/downloads/

I have only tested of the linux versions (harp_linux_140925_103521.zip), so I can't speak for the OSX version, but I was able to get it running. 

Couple of months too late, but hope it helps someone else. :)
