### ISSUE TITLE
Wrong file naming for `simpute` method

### ISSUE THREAD

**Issue by lczech** [petrov-lab/HAFpipe-line#4]
Hi there!

There is a mismatch between the file names of the imputed table when using Task 2 with "simpute", and what Task 3 then expects as input.

In particular, [see here](https://github.com/petrov-lab/HAFpipe-line/blob/0b773910ee625aacc5c7a43f9cf1a7f0eb6c5da2/HAFpipe_wrapper.sh#L228) for the command that calls Task 2, to create a table with the suffix `.simpute`. However, Task 2 actually names this file using the suffix `.imputed` instead, [see here](https://github.com/petrov-lab/HAFpipe-line/blob/0b773910ee625aacc5c7a43f9cf1a7f0eb6c5da2/impute_SNPtable.sh#L20). Then, when Task 3 is called, [see here](https://github.com/petrov-lab/HAFpipe-line/blob/0b773910ee625aacc5c7a43f9cf1a7f0eb6c5da2/HAFpipe_wrapper.sh#L258), it does not find the table, as it is looking for the file with suffix `.simpute` instead. HAFpipe needs to be restarted with `--impmethod imputed` instead of `simpute` to fix this at the moment, which does not seem ideal.

Cheers
Lucas

**Comment by greensii** [comment]
Thank you for catching this! My apologies, i was not getting any notifications about issues/pull requests, so i am just seeing this now. But i am reviewing your pull request and really appreciate your improvements.
